<definitions name="WalletService"
             targetNamespace="http://example.com/walletservice"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://example.com/walletservice"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="createWalletRequest">
        <part name="walletData" type="xsd:string"/>
    </message>

    <message name="createWalletResponse">
        <part name="success" type="xsd:boolean"/>
        <part name="cod_error" type="xsd:string"/>
        <part name="message_error" type="xsd:string"/>
        <part name="data" type="xsd:string"/>
    </message>

    <message name="updateWalletRequest">
        <part name="id" type="xsd:int"/>
        <part name="walletData" type="xsd:string"/>
    </message>

    <message name="updateWalletResponse">
        <part name="success" type="xsd:boolean"/>
        <part name="cod_error" type="xsd:string"/>
        <part name="message_error" type="xsd:string"/>
        <part name="data" type="xsd:string"/>
    </message>

    <portType name="WalletServicePortType">
        <operation name="createWallet">
            <input message="tns:createWalletRequest"/>
            <output message="tns:createWalletResponse"/>
        </operation>
        <operation name="updateWallet">
            <input message="tns:updateWalletRequest"/>
            <output message="tns:updateWalletResponse"/>
        </operation>
    </portType>

    <binding name="WalletServiceBinding" type="tns:WalletServicePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="createWallet">
            <soap:operation soapAction="http://example.com/walletservice/createWallet"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="updateWallet">
            <soap:operation soapAction="http://example.com/walletservice/updateWallet"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="WalletService">
        <documentation>Wallet Service</documentation>
        <port name="WalletServicePort" binding="tns:WalletServiceBinding">
            <soap:address location="http://localhost:8001/wsdl"/>
        </port>
    </service>
</definitions>