<definitions name="CustomerService"
             targetNamespace="http://example.com/customerservice"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://example.com/customerservice"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="registerCustomerRequest">
        <part name="document" type="xsd:string"/>
        <part name="fullName" type="xsd:string"/>
        <part name="email" type="xsd:string"/>
        <part name="phone" type="xsd:string"/>
    </message>

    <message name="registerCustomerResponse">
        <part name="success" type="xsd:boolean"/>
        <part name="cod_error" type="xsd:string"/>
        <part name="message_error" type="xsd:string"/>
        <part name="data" type="xsd:string"/>
    </message>

    <portType name="CustomerServicePortType">
        <operation name="registerCustomer">
            <input message="tns:registerCustomerRequest"/>
            <output message="tns:registerCustomerResponse"/>
        </operation>
    </portType>

    <binding name="CustomerServiceBinding" type="tns:CustomerServicePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="registerCustomer">
            <soap:operation soapAction="http://example.com/customerservice/registerCustomer"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="CustomerService">
        <documentation>Customer Service</documentation>
        <port name="CustomerServicePort" binding="tns:CustomerServiceBinding">
            <soap:address location="http://localhost:8001/wsdl"/>
        </port>
    </service>
</definitions>